### ISSUE TITLE
Potential collision of header files between Cifti and other libraries

### ISSUE THREAD

**Issue by ghisvail** [Washington-University/CiftiLib#11]
This is the list of headers installed by CiftiLib:

```
-- Installing: ./usr/local/include/Cifti/NiftiHeader.h
-- Installing: ./usr/local/include/Cifti/NiftiIO.h
-- Installing: ./usr/local/include/Cifti/CiftiFile.h
-- Installing: ./usr/local/include/Cifti/CiftiXML.h
-- Installing: ./usr/local/include/Cifti/CiftiVersion.h
-- Installing: ./usr/local/include/Cifti/CiftiMappingType.h
-- Installing: ./usr/local/include/Cifti/CiftiBrainModelsMap.h
-- Installing: ./usr/local/include/Cifti/CiftiLabelsMap.h
-- Installing: ./usr/local/include/Cifti/CiftiParcelsMap.h
-- Installing: ./usr/local/include/Cifti/CiftiScalarsMap.h
-- Installing: ./usr/local/include/Cifti/CiftiSeriesMap.h
-- Installing: ./usr/local/include/Cifti/Label.h
-- Installing: ./usr/local/include/Cifti/LabelTable.h
-- Installing: ./usr/local/include/Cifti/MetaData.h
-- Installing: ./usr/local/include/Cifti/StructureEnum.h
-- Installing: ./usr/local/include/Cifti/VolumeSpace.h
-- Installing: ./usr/local/include/Cifti/AString.h
-- Installing: ./usr/local/include/Cifti/ByteSwapping.h
-- Installing: ./usr/local/include/Cifti/CiftiAssert.h
-- Installing: ./usr/local/include/Cifti/BinaryFile.h
-- Installing: ./usr/local/include/Cifti/CiftiException.h
-- Installing: ./usr/local/include/Cifti/Compact3DLookup.h
-- Installing: ./usr/local/include/Cifti/CompactLookup.h
-- Installing: ./usr/local/include/Cifti/MultiDimIterator.h
-- Installing: ./usr/local/include/Cifti/Vector3D.h
-- Installing: ./usr/local/include/Cifti/VoxelIJK.h
-- Installing: ./usr/local/include/Cifti/XmlAdapter.h
```

And the pkgconfig file adds `/usr/local/include/Cifti` to the compiler's list of include directories. I think headers prefixed with `Cifti` or `Nifti` should be fine, but there is potential for file collision with generic names such as `Label.h` or `Vector3D.h` in the include paths, especially if multiple neuroimaging libraries are mixed with CiftiLib in a future project.

Perhaps you should consider using namespaced includes, i.e. doing:
# include "Cifti/Voxel3D.h"

And in that case, the solution is to just replace the following line in the pkgconfig file:

```
Cflags: -I${includedir}/Cifti @CIFTILIB_PKGCONFIG_DEFINE@
```

with:

```
Cflags: -I${includedir} @CIFTILIB_PKGCONFIG_DEFINE@
```

If you are happy with this solution Tim, please consider making a micro release. Some headers and examples may need adjustments as a result of the change.

Cheers,
Ghis

**Comment by coalsont** [comment]
I have seen a potential conflict of this kind in DTI-TK, but it didn't occur to me at the time to make a change.  I do want to fix this.

Unfortunately, it is a little messier than your proposed solution, as the directory structure of the headers at compile time is currently different than at install time.  After some thought, I think it would be simplest to add "Cifti" to the filename of all headers that seem likely to conflict (everything in Common that doesn't already have it), and leave the pkgconfig file as-is.  Thoughts?

**Comment by coalsont** [comment]
Should the library version (in CMakeLists.txt, controlling the .so filename and how many symlinks are made) include the micro version number, or just major and minor?

To be perfectly clear, the issue with requiring a path in the includes is that most of the headers include other headers (almost everything ends up including Common/AString.h, as it is the unicode string implementation placeholder), which are in "Common", "Nifti", or "Cifti" at compile time, but are all in a "Cifti" directory after install (this could be renamed "CiftiLib" or such for clarity, its main purpose is to keep the various installed CiftiLib headers together in one place, rather than interspersed with many other library headers - if this is undesired and/or nonstandard, it can be removed, but that requires making the include names more unique).

For reference, the options I see are:
- add "Cifti" to the beginning of relevant include file names to remove conflict potential, and have the include directories from the build system (both library building and end-user) hide the differences in directory structure, never needing to specify in the source what subdirectory the include should be found in
- removing the directory structure in the source tree (but I like the organization the way it is for development)
- adding #ifdef magic (or worse, install-time editing of headers) around include statements depending on whether we are building CiftiLib or just linking to it (kind of ugly)
- adding the source directory structure to the installed headers (might be confusing for end users)

**Comment by ghisvail** [comment]
> [...] if this is undesired and/or nonstandard, it can be removed, but that requires making the include names more unique).

I don't think it is either undesired or non-standard, the main issue at the moment is the potential for file collision for those headers with fairly generic names such as `Label.h` for instance.

As for the options you listed:

> add "Cifti" to the beginning of relevant include file names to remove conflict potential

Prefixing `Cifti` to all files is possible but not particularly modern. There are better options I believe.

> removing the directory structure in the source tree

The current directory structure may be getting in the way indeed. Since `Common`, `Nifti` and `Cifti` ends up combined to the same DSO, their separation just make the build system unnecessarily complicated.

> adding #ifdef magic (or worse, install-time editing of headers) around include statements depending on whether we are building CiftiLib or just linking to it (kind of ugly)

Indeed, ugly and definitely non-standard.

> adding the source directory structure to the installed headers

Not sure what you mean here.

In my experience as a package maintainer and developer, modern C++ libraries tend to adopt the following design:
- one public header (Cifti.h for instance) located under the `$INCLUDE_INSTALL_PATH` and containing relative imports to the rest of the headers composing the library.
- the rest of the headers are installed in a private directory location under `$INCLUDE_INSTALL_PATH` (for instance `$INCLUDE_INSTALL_PATH/cifti`)

A good example of this structure is [ArrayFire](https://github.com/arrayfire/arrayfire), where the only public header is `arrayfire.h`, and the rest of the headers is hidden under an `af` subdir.

The intent for the end-user is also very clear: you are supposed to only include this single public header to use the library. Consequently, it shields client code using the library from potential re-arrangements of the headers under the private subdir. The name of the subdir is often chosen to somewhat match the namespace of the library (here `cifti`) but it is not an official convention.

Let me know if any of these points is not clear enough.

**Comment by coalsont** [comment]
> > adding the source directory structure to the installed headers
> 
> Not sure what you mean here.

I meant install headers to $PREFIX/CiftiLib/Common, $PREFIX/CiftiLib/Nifti, as they exist in the current structure.  It doesn't seem like a good idea by itself, but it could be used for the headers the end-user doesn't include directly (keeping some desired structure in the source tree).

> one public header (Cifti.h for instance) located under the $INCLUDE_INSTALL_PATH and containing relative imports to the rest of the headers composing the library.

That sort of already happens, as the includes of CiftiFile.h cover most of the Cifti directory and some of the Common directory (NiftiIO.h is the other main entry point, but there is also the MultiDimIterator helper which should also be exposed, but not necessarily included by default).  I may have previously been thinking of "private headers" as "containing types the end-user doesn't see", resulting in the wrong impression of what to do there.  I'll think about which headers should be directly included in end-user code.

**Comment by coalsont** [comment]
Take a look at https://github.com/Washington-University/CiftiLib/tree/reorganize and let me know how far off-track I am.

Short version: pkgconfig now has `-I/usr/include/CiftiLib`, which contains CiftiFile.h, NiftiIO.h, and MultiDimIterator.h, the rest of the headers are in `/usr/include/CiftiLib/Common`, `/usr/include/CiftiLib/Cifti`, and `/usr/include/CiftiLib/Nifti`

In the process, I discovered the "look in same directory first" behavior of including with "" for at least gcc and clang, and used it shamelessly (update: MSVC compiles them okay, with some unrelated other fixes).  I didn't simplify the build system, either, because I don't really want to mix Common and Cifti (Nifti is a little anemic, but as long as I have more than one subdirectory anyway...).

**Comment by coalsont** [comment]
Oh, it also installs all headers into those subdirectories that don't get a `-I`, rather than leaving out the ones that are only included by .cxx files, and thus aren't included even indirectly by end-users.  This could be changed.

**Comment by coalsont** [comment]
@ghisvail Did you have any comments on the reorganization in that branch?

**Comment by ghisvail** [comment]
Apologize for the late reply, had other stuff going on lately. I have had a look at the layout of the source and install trees and still have a few questions / observations. Here they are:
- What is the purpose of exposing `MultiDimIterator.h`? I thought it would be available under `Common` considering how generic this is. Besides, given the name of the file, there is still potential for name clashing with other libs, no?
- CiftiFile.h uses the pimpl idiom using a `boost::shared_ptr`, meaning client code using CiftiLib would have to depend on Boost. Such boundary effect is not considered good practice. Instead, it should probably be replaced by a raw pointer, or better, a `std::unique_ptr` with a requirement on C++11 onwards.
- NiftiIO.h exposes quite a bit of the CiftiLib runtime. I understand that this comes from because of the usage of templated functions, so an explicit implementation has to be provided. I was just wondering whether this could be optimized somehow.

**Comment by coalsont** [comment]
> What is the purpose of exposing MultiDimIterator.h? I thought it would be available under Common considering how generic this is. Besides, given the name of the file, there is still potential for name clashing with other libs, no?

See example/rewrite.cxx for how would be used in end-user code - Cifti currently supports both 2 and 3 matrix dimensions (and may support more in the future), and this helper exists to flatten the dimensions beyond rows (actually, it is more generic, and the user has to remove the rows dimension from the dimensions given to the iterator).  It could also be useful for using NiftiIO (up to 7 dimensions).  The include probably should be renamed to avoid conflicts (and maybe the class itself, even though it is more generic than CIFTI).  I could stick it in Common instead, and #include it from CiftiFile.h, but many uses of CiftiFile don't need it (ie, if you write something that only accepts 2D cifti).

> CiftiFile.h uses the pimpl idiom using a boost::shared_ptr, meaning client code using CiftiLib would have to depend on Boost. Such boundary effect is not considered good practice. Instead, it should probably be replaced by a raw pointer, or better, a std::unique_ptr with a requirement on C++11 onwards.

I'd rather not make it require C++11, and raw pointers would get messy, as it is not as simple as a pimpl idiom (see CiftiFile::verifyWriteImpl(), it does (smart)pointer assignment and file IO using exceptions).  It looks like std::auto_ptr isn't good enough to replace it for this use (needs to have a pointer shared between two holders to make the on-disk read vs write code work), so for C++03 it will have to continue to rely on boost (which it also uses for more things when QT isn't available anyway), unless I roll my own shared_ptr replacement.  Probably the best solution is to use a typedef in an #ifdef guard to switch it to std::shared_ptr in C++11 and beyond.

> NiftiIO.h exposes quite a bit of the CiftiLib runtime. I understand that this comes from because of the usage of templated functions, so an explicit implementation has to be provided. I was just wondering whether this could be optimized somehow.

As in, the header files it includes?  I see two mitigating factors:
- all classes are namespaced inside of 'cifti', so those won't collide in code
- the NiftiIO header isn't included by other headers, so it only affects end user files that want to directly use the lower-level nifti reading.

I could change the asserts to throws, I suppose, even though they are programming errors, and not unexpected input errors (though if the programmer doesn't expect 3D cifti...).  I had also previously wondered if it was kosher to use asserts of the #ifndef NDEBUG #define variety in header files.

The byteswapping could be hidden with some effort (either use private overloads to handle disk datatype, or pass into private function as void*, do the disk-side templates inside the .cxx file, and keep the templated public function signatures), but it doesn't include anything else, so may not be worth it (though it would remove two big ugly switches from the header...).

The BinaryFile prototype could probably be hidden with some effort (changing it to some flavor of pointer and redirecting through a member function in NiftiIO and NiftiHeader), but as it only exposes that one additional class (since AString is in the interface of NiftiIO), I don't know that it is worth it.

NiftiHeader is also part of the interface, which winds up including nifti1.h and nifti2.h, which people dealing with low-level NIfTI IO are almost certainly expecting.

**Comment by coalsont** [comment]
> > CiftiFile.h uses the pimpl idiom using a boost::shared_ptr, meaning client code using CiftiLib would have to depend on Boost. Such boundary effect is not considered good practice. Instead, it should probably be replaced by a raw pointer, or better, a std::unique_ptr with a requirement on C++11 onwards.
> 
> I'd rather not make it require C++11, and raw pointers would get messy, as it is not as simple as a pimpl idiom (see CiftiFile::verifyWriteImpl(), it does (smart)pointer assignment and file IO using exceptions). It looks like std::auto_ptr isn't good enough to replace it for this use (needs to have a pointer shared between two holders to make the on-disk read vs write code work), so for C++03 it will have to continue to rely on boost (which it also uses for more things when QT isn't available anyway), unless I roll my own shared_ptr replacement. Probably the best solution is to use a typedef in an #ifdef guard to switch it to std::shared_ptr in C++11 and beyond.

This is a little trickier than I thought - I have it compiling with an alias for shared_ptr in cifti namespace to either std or boost, but if the library gets built without C++11 enabled, and included by a project that builds explicitly enabling C++11, it will probably break as the header definition ends up using different types than the library.  Maybe I could have cmake test for C++11 being requested, and stick a define into the pkgconfig file, but this is getting messy.  Is boost::shared_ptr really so bad if the headers don't put it into global namespace?

**Comment by coalsont** [comment]
> The byteswapping could be hidden with some effort (either use private overloads to handle disk datatype, or pass into private function as void*, do the disk-side templates inside the .cxx file, and keep the templated public function signatures), but it doesn't include anything else, so may not be worth it (though it would remove two big ugly switches from the header...).

I don't know what I was thinking of here.  If the functions for reading and writing use templates to handle any memory-side datatype, then the conversion to those types has to happen in the header, which means it needs a switch based on the on-disk type.  It could go through a private function solely to hide the byteswapping (and potentially binary file) include, but it wouldn't make the code any cleaner.

I have pushed commits to remove asserts in some headers (there are still some in CompactLookup.h that gets included through CiftiFile.h - no members of it get called from a header-implemented function, so I think it is relatively safe) and rename MultiDimIterator.h.  The other things are technically possible, but somewhat painful (moving members to pimpl, more defines in pkgconfig) - how important are they?

**Comment by ghisvail** [comment]
>  Is boost::shared_ptr really so bad if the headers don't put it into global namespace?

It is "bad" in a sense that you intentionally leak a dependency on Boost for client code. It was fine with C++98 / 03 because the standard library was limited, so Boost was a reasonable dependency to have. Now with the growing availability of C++11, especially for things like this, the extra dependency on Boost is unnecessary. Depends how much you care at the end of the day.

>  It could go through a private function solely to hide the byteswapping (and potentially binary file) include, but it wouldn't make the code any cleaner.

Then don't. These are remarks I made from an outside view of the code. It does not mean they should all be addressed. I don't think code clarity should be sacrificed.

> and rename MultiDimIterator.h

I am still unsure about exposing (Cifti)MultiDimIterator.h TBH. Looking at the body, it is fairly generic and not tied to the Cifti runtime that much. Same observation for `Common/MultiDimArray.h` for instance.

Perhaps you could have the iterator embedded into `CiftiFile` instead. As a result, client code would not have to handle the instantiation of the iterator itself (like it is done in `example/rewrite.cxx`) but borrow it from a working instance of `CiftiFile`. Then `CiftiFile.h` would import `Common/MultiDimIterator` thereby simplifying your public interface.

> The other things are technically possible, but somewhat painful (moving members to pimpl, more defines in pkgconfig) - how important are they?

Depends how much you are committed to providing a stable API / ABI. Nice thing with pimpl is that it gives you freedom to reorganize things as the Cifti format evolves. If the format is unlikely to change and you are happy with the state of the API, then none of my remarks is a deal breaker.

**Comment by coalsont** [comment]
> > Is boost::shared_ptr really so bad if the headers don't put it into global namespace?
> 
> It is "bad" in a sense that you intentionally leak a dependency on Boost for client code. It was fine with C++98 / 03 because the standard library was limited, so Boost was a reasonable dependency to have.

I want it to continue to work on C++03 (freesurfer compiles using centos 6 and ubuntu 12.04 as their newest distros, and freesurfer is looking into using CiftiLib), so it sounds like this is reasonable for now.  Removing it can wait until making it ABI stable, as the best solution to it is pimpl.

> Perhaps you could have the iterator embedded into CiftiFile instead. As a result, client code would not have to handle the instantiation of the iterator itself (like it is done in example/rewrite.cxx) but borrow it from a working instance of CiftiFile. Then CiftiFile.h would import Common/MultiDimIterator thereby simplifying your public interface.

Perhaps a "createIteratorOverRows" convenience function would be nice, to encourage people to try to support cifti with 3 dimensions (in a way that could work with more dimensions in a future version).  If they wanted to use it with NiftiIO, they'd also need to include CiftiFile.h then, unless I added it as an include to both headers (even though neither class currently depends on it in the interface).

> > The other things are technically possible, but somewhat painful (moving members to pimpl, more defines in pkgconfig) - how important are they?
> 
> Depends how much you are committed to providing a stable API / ABI. Nice thing with pimpl is that it gives you freedom to reorganize things as the Cifti format evolves. If the format is unlikely to change and you are happy with the state of the API, then none of my remarks is a deal breaker.

The purpose of the format is fixed, and format version 2.0, from an API view, only added new mapping types that can be used (though that does extend an important enum, which could break code that doesn't contain a failsafe default case).  The API doesn't expose the current 3 dimension limit (it errors only when you try to actually write a 4+D one), so it is fairly stable.  However, making it ABI stable is not on my priorities, could take a significant amount of time, and I have other things that need my time currently.

**Comment by coalsont** [comment]
> > Perhaps you could have the iterator embedded into CiftiFile instead. As a result, client code would not have to handle the instantiation of the iterator itself (like it is done in example/rewrite.cxx) but borrow it from a working instance of CiftiFile. Then CiftiFile.h would import Common/MultiDimIterator thereby simplifying your public interface.
> 
> Perhaps a "createIteratorOverRows" convenience function would be nice, to encourage people to try to support cifti with 3 dimensions (in a way that could work with more dimensions in a future version). If they wanted to use it with NiftiIO, they'd also need to include CiftiFile.h then, unless I added it as an include to both headers (even though neither class currently depends on it in the interface).

I have made this change also.  The other reorganization changes suggested so far don't seem to be important or simple enough to tackle at this time.  There are a few other things to fix, and then I'll make a minor release.

**Comment by coalsont** [comment]
I have made release v1.5 based on this reorganization, plus some other improvements

**Comment by ghisvail** [comment]
Looks good to me :+1:
