### ISSUE TITLE
Convert Cifti to Nifti

### ISSUE THREAD

**Issue by acamargofb** [Washington-University/CiftiLib#25]
Hi there,

One question, how can I use this library to convert cifti to nifti ? I have used this library to read and do some computations in a cifti library,I can save it as nifti, but I would like to save it as  nifti.

Any idea will be helpful,

Aldo

**Comment by coalsont** [comment]
This library does have low-level nifti-1 read/write capabilities, however it does not have any of the geometry code needed to turn vertex-based data into something that actually displays as a volume file (so you could only convert the subcortical and cerebellar data from typical cifti files).  If you want "fake nifti" to trick volume-based tools that don't use neighborhood information into running on vertex-based data, that wouldn't be too challenging, but you might as well use `wb_command -cifti-convert` for that instead of writing your own.

As for the more complicated task of mapping surface data to the volume, we generally don't advise doing that, as human cortical surface-based data is almost always better aligned across subjects than its volume equivalent (see our paper https://www.pnas.org/content/115/27/E6356).  It is valid to map surface data to an individual's volume space using that individual's surfaces, but it is generally not valid to try to map it to a group average volume space.  `wb_command -metric-to-volume-mapping` has implemented this capability for one hemisphere at a time (you need to decide how to deal with voxels that both surfaces interact with).
